// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZK7MOxiAwKRXEPEL-TPWbNVeb5szq1I',
    appId: '1:602318106929:web:e4afef17454e2166ebc010',
    messagingSenderId: '602318106929',
    projectId: 'todolist-31858',
    authDomain: 'todolist-31858.firebaseapp.com',
    storageBucket: 'todolist-31858.appspot.com',
    measurementId: 'G-Y84QCLFT3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRh2i9RCRaNGb0m7tIPTDEN_85Fcl_xJ8',
    appId: '1:602318106929:android:e48978d70584fcecebc010',
    messagingSenderId: '602318106929',
    projectId: 'todolist-31858',
    storageBucket: 'todolist-31858.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuSwP0JtWKzPvy4BLbYxn1EOozt8vsukg',
    appId: '1:602318106929:ios:ac394d8fd7a5a736ebc010',
    messagingSenderId: '602318106929',
    projectId: 'todolist-31858',
    storageBucket: 'todolist-31858.appspot.com',
    iosBundleId: 'com.example.todoPractice.RunnerTests',
  );
}
